# Set server hostname
#- hostname:
#    name: puppet-master.gordonmurray.com
#    use: debian

#  enable the universe repository, which contains packages necessary for Puppet Server
- name: Enable universe repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
    update_cache: True

# Install Puppet deb
- name: Install Puppet .deb
  apt:
    deb: https://apt.puppet.com/puppet6-release-bionic.deb

# Install packages
- name: Install packages
  vars:
    packages:
      - ntp
      - puppetserver
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

# Puppet Java process memory allocation
- name: Copy file with owner and permissions
  copy:
    src: puppet-master
    dest: /etc/default/puppet-master

- name: Make sure a service is running
  systemd:
    state: started
    name: puppetserver.service

- name: enable service
  systemd:
    name: puppetserver.service
    enabled: yes
