- name: Download Puppet MSI
  win_get_url:
    url: https://downloads.puppetlabs.com/windows/puppet5/puppet-agent-5.5.21-x64.msi
    dest: C:\temp\puppet-agent-5.5.21-x64.msi

- name: Install Puppet MSI
  win_package:
    path: C:\temp\puppet-agent-5.5.21-x64.msi
    state: present